### ISSUE TITLE
32x48 Humanoid Tileset

### ISSUE THREAD

**Issue by BBlankie** [SomeDeadGuy/Cata-MSX-DeadPeopleTileset#20] opened 2019-02-22 03:35 UTC
Hiya, I’m wondering if you can do what Xotto perviously planned to do.

![97cda40e-2f31-439b-bda6-f7b9862c0210](https://user-images.githubusercontent.com/44106380/53217932-fed5e080-3694-11e9-8328-036904ec6b2d.jpeg)

If you don’t want to rework 90% of your tileset, then it’s okay.
If you’re willing to do it, then it’s greatly appreciated. (it could be a seperate tileset or one of your tileset mods like the indicators)

**Comment by SomeDeadGuy** [comment] 2019-02-23 02:51
I would do that, if i did got nothing more to do.
Sadly i have many years worth of tiles to make. We need another me, then he can make it. :D

**Comment by SomeDeadGuy** [comment] 2019-02-23 02:52
Gonna close this. Not an possible thing to do in near future and not a bug in tileset. :P

**Closed by SomeDeadGuy** 2019-02-23 02:52 UTC
